### ISSUE TITLE
dataset type and running error 

### ISSUE THREAD

**Issue by lrmaxin** [chiarabales/FSFC#2]
Are there any requirements for the input data set? Does it have to be an integer? Why do I get an error when I use a data set of type Double as my mydata

**Comment by chiarabales** [comment]
The data type is set to be discrete and categorical as the approach includes the computation of Shannon Entropy. Using only discrete data does not require an estimation of Shannon Entropy.

Two solutions are possible for you:
- discretize your data
- change the SU function with a continuous estimation of the entropy (i.e., differential entropy). I have not worked on this second option yet

**Comment by lrmaxin** [comment]
thank you ！
